---
title: "SPRIS Project 3"
author: "Jessica Lavery"
date: "3/31/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(gtsummary)
library(mice)

load(here::here("datasets.rdata"))

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

# Table 1

```{r}
data_expanded %>% 
  distinct(subject_id, treatment_group, age, gender) %>% 
  select(-subject_id) %>% 
  tbl_summary(by = treatment_group) %>% 
  add_overall()
```

# Spaghetti plot for patient trajectories over time

```{r}
data_expanded %>% 
  mutate(measurement_time = case_when(
    day == 0 ~ 1,
    day == 5 ~ 2,
    day == 19 ~ 3,
    day == 90 ~ 4
  )) %>% 
  ggplot(aes(x = day, y = mem_comp)) +
  geom_point(aes(color = treatment_group, group = subject_id)) +
  geom_line(aes(color = treatment_group, group = subject_id)) +
  geom_smooth(color = "gray", size = 2, method = "loess", se = FALSE) +
  labs(x = "Day",
       color = "Treatment",
       y = "Cognitive Rating",
       caption = "Higher cognitive rating indicates better memory.") +
  facet_grid(.~treatment_group)
```

# Numeric summary of average cognitive scores over time, by treatment

```{r}
data_expanded %>% 
  tbl_summary(by = treatment_group,
              include = c(treatment_group, mem_comp))
```